# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    env:
      working-directory: ./

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install libpmemkv with deps
      run: sudo apt install libpmemkv-dev

    - name: Build pmemkv module of YCSB
      run: mvn -pl site.ycsb:pmemkv-binding -am package
